return {
  {
    "adibhanna/laravel.nvim",
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
    },
    cmd = {
      "Artisan",
      "Composer",
      "LaravelMake",
      "LaravelRoute",
      "LaravelStatus",
      "ComposerRequire",
      "ComposerRemove",
      "ComposerDependencies",
      "Sail",
      "SailUp",
      "SailDown",
      "SailRestart",
      "SailTest",
      "SailShare",
      "SailShell",
      "LaravelDumps",
      "LaravelDumpsInstall",
      "LaravelDumpsEnable",
      "LaravelDumpsDisable",
      "LaravelDumpsToggle",
      "LaravelDumpsClear",
      "LaravelGoto",
    },
    keys = {
      { "<leader>la",  ":Artisan<cr>",              desc = "Laravel Artisan" },
      { "<leader>lc",  ":Composer<cr>",             desc = "Laravel Composer" },
      { "<leader>lr",  ":LaravelRoute<cr>",         desc = "Laravel Routes" },
      { "<leader>lm",  ":LaravelMake<cr>",          desc = "Laravel Make" },
      { "<leader>ls",  ":LaravelStatus<cr>",        desc = "Laravel Status" },
      { "<leader>lR",  ":ComposerRequire<cr>",      desc = "Composer Require" },
      { "<leader>lx",  ":ComposerRemove<cr>",       desc = "Composer Remove" },
      { "<leader>lD",  ":ComposerDependencies<cr>", desc = "Composer Dependencies" },
      { "<leader>ld",  ":LaravelDumps<cr>",         desc = "Laravel Dumps" },
      { "<leader>lDe", ":LaravelDumpsEnable<cr>",   desc = "Enable Dump Capture" },
      { "<leader>lDd", ":LaravelDumpsDisable<cr>",  desc = "Disable Dump Capture" },
      { "<leader>lDt", ":LaravelDumpsToggle<cr>",   desc = "Toggle Dump Capture" },
      { "<leader>lDc", ":LaravelDumpsClear<cr>",    desc = "Clear Dumps" },
      { "gd",          ":LaravelGoto<cr>",          desc = "Laravel Goto",         ft = "php" },
    },
    ft = { "php", "blade" },
    config = function()
      require("laravel").setup({
        notifications = true,
        debug = false,
        keymaps = true,
        sail = {
          enabled = true,
          auto_detect = true,
        },
      })
    end,
  },
}
