return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "php",
        "phpdoc",
        "blade",
        "javascript",
        "typescript",
        "tsx",
        "jsdoc",
        "vue",
        "html",
        "css",
        "scss",
        "json",
        "jsonc",
        "yaml",
        "markdown",
        "markdown_inline",
        "lua",
        "vim",
        "vimdoc",
        "bash",
        "clojure",
        "python",
        "elixir",
        "heex",
        "eex",
      },
      highlight = {
        enable = true,
      },
      indent = {
        enable = true,
      },
    },
  },
}
